sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

services:
    admin.post:
        class: App\Admin\BlogAdmin
        arguments: [~, App\Entity\Post, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, label: Посты }

